---

# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    steps:
      - run: |+
          echo "pwd: $(pwd)"
          ls
          echo
          echo "done"
          echo


