
# https://circleci.com/docs/2.0/configuration-reference
version: 2

only-master-branch: &only-master-branch
  filters:
    branches:
      only:
        - master


#executors:
#  "gh-aws-node-python":
#    docker:
#      - image: devokun/gh-aws-node-python:latest

jobs:
  executeOrder66:
    environment:
      HELLO: WORLD
      S3_BUCKET: "makepass.net"
    #executor: "gh-aws-node-python"
    docker:
      #- image: cimg/base:2020.01
      - image: cimg/ruby:2.6.5
    steps:
      - checkout

      - run:
          name: ruby version
          shell: /bin/bash
          command: ruby --version

      - run:
          name: install s3_website
          shell: /bin/bash
          command: |+
            gem install s3_website --no-doc
            s3_website install

      - run:
          name:    'info'
          shell:   '/bin/bash'
          command: |+
            echo
            echo "S3 Bucket: ${S3_BUCKET}"
            echo "pwd......: $(pwd)"
            ls
            echo
            echo "done"
            echo

workflows:
  version: 2
  dewit:
    jobs:
      - executeOrder66: *only-master-branch


